export const words = [
  "Love",
  "anthony",
  "marcia",
  "26th August",
  "2023",
  "Wedding",
  "life",
  "Our New Beginning",
  "26th August 2023",
  "Join Us",
  "26th August 2023",
  "change",
  "26th August 2023",
  "Our experience",
  "Our Special Day",
  "26th August 2023",
  "Anthony",
  "26th August 2023",
  "We Welcome",
  "You to our special Day",
  "Marcia",
  "Love",
  "Join Us",
  "26th August 2023",
  "experience",
  "26th August 2023",
  "Love",
  "Marcia",
  "Anthony",
  "chance",
  "26th August 2023",
  "Our Moment",
  "Celebrate Our Love",
  "Join Us",
  "Our Love",
  "experience",
  "interaction",
  "26th August 2023",
  "Our Love",
  "26th August",
  "Our Love",
  "Anthony",
  "Our Love Meet",
  "Marcia",
  "26th",
  "August",
  "Love",
  "Our Wedding",
  "A&M",
  "Anthony Weds Marcia 2023",
  "26th",
  "26th August 2023",
  "The Merge",
  "The Main Event",
  "Love",
];
